### ISSUE TITLE
运行提示数据库连接失败

### ISSUE THREAD

**Issue by l277978707** [migomiddle/xms#11]
System.Data.SqlClient.SqlException:“A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)”

**Comment by l277978707** [comment]
没有人遇到类似的问题吗

**Comment by snowiceyeah** [comment]
同问，我也是这个错误，之前还好使 和我升级了vs有关系么

**Comment by snowiceyeah** [comment]
![image](https://user-images.githubusercontent.com/43429385/77147420-27aeec00-6ac8-11ea-921e-d96214a21935.png)
需要在confconfig里改一下连接配置

**Comment by l277978707** [comment]
谢谢，重新加载，运行调试，出现新的提示，是不是和我的开发环境有关。System.ArgumentException:“Could not load the SqlServerDatabaseProvider DbProviderFactory.”

**Comment by l277978707** [comment]
更新下SqlServerDatabaseProvider DbProviderFactory就好了
